# 实验1. 机器学习实验基础(Numpy)

In [1]:
import numpy as np

# 1. 数据读取、数据属性

In [2]:
print('Loading data ...')
# 1. 装载数据集
data = np.loadtxt('./house_price.txt', delimiter=',')

# 2. 打印数据集的维度数，及各维度的尺寸
print(data.shape, data.ndim)
print("Size of data is :", data.shape , ", and dimension is", data.ndim )

# 3. 打印样本个数和样本维度
m = data.shape[0]
n = data.shape[1]
print('样本个数：', m, '样本维度：', n)

Loading data ...
(47, 3) 2
Size of data is : (47, 3) , and dimension is 2
样本个数： 47 样本维度： 3


# 2. 数据切片与检索

In [3]:

#1. 读取前两列作为输入X (二维数组)
X = data[:, 0:2]

#2. 读取第3列作为y （一维数组）
y = data[:, 2]
print(y.shape, y.ndim)

#3. 读取第3列作为y （m*1的二维矩阵）
y = data[:, [2]]
print(y.shape, y.ndim)

#4. 显示前10条房价数据
print(data[:10, :])

#5. 显示房价低于20万的房屋数据（for循环、逻辑表达式）
y = data[:, 2]
index = y < 200000
print(index)
cheapHouse = X[index,:]
print(cheapHouse)


(47,) 1
(47, 1) 2
[[2.10400e+03 3.00000e+00 3.99900e+05]
 [1.60000e+03 3.00000e+00 3.29900e+05]
 [2.40000e+03 3.00000e+00 3.69000e+05]
 [1.41600e+03 2.00000e+00 2.32000e+05]
 [3.00000e+03 4.00000e+00 5.39900e+05]
 [1.98500e+03 4.00000e+00 2.99900e+05]
 [1.53400e+03 3.00000e+00 3.14900e+05]
 [1.42700e+03 3.00000e+00 1.98999e+05]
 [1.38000e+03 3.00000e+00 2.12000e+05]
 [1.49400e+03 3.00000e+00 2.42500e+05]]
[False False False False False False False  True False False False False
 False False False False False  True False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False  True False False]
[[1.427e+03 3.000e+00]
 [1.236e+03 3.000e+00]
 [1.000e+03 1.000e+00]
 [8.520e+02 2.000e+00]]


# 1. 数组创建
创建空数组、全零、全一、随机、序列数组

##### 1.1 空数据 numpy.empty(shape, dtype=float, order='C')
order：是否在内存中以C或fortran(C或F，行或列)顺序存储多维数据

In [4]:
x1 = np.empty([4, 3])
x1

array([[1.10507504e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 6.23059386e-307, 4.42419353e-062],
       [2.44998203e-056, 1.38138838e-047, 2.27285373e+184],
       [5.40223333e-062, 2.25568964e+180, 3.29466003e-032]])

##### 1.2 全零 numpy.zeros(shape, dtype = float, order = 'C')，zeros_like()  

In [5]:
x2 = np.zeros((4, 3))
x2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### 1.3 全一 numpy.ones(shape, dtype = None, order = 'C') 

In [6]:
x3 = np.ones((47, 1))
x3

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

##### 1.4 随机 numpy.random.random()

In [7]:
x4 = np.random.random([3,2])
print(x4)

[[0.27039165 0.98710189]
 [0.35870199 0.63134534]
 [0.63659286 0.26694452]]


##### 1.5 生成序列

In [8]:
x5 = np.arange(9)
print(x5)

[0 1 2 3 4 5 6 7 8]


# 2. 数组操作 

##### 2.1 数组的转置
对X分别使用numpy.transpose(arr, axes)和numpy.ndarray.T进行转置

In [9]:
# 使用 numpy.ndarray.T 进行转置
X_T1 = X.T
print("T属性转置:\n", X_T1.shape)

# 使用 numpy.transpose 进行转置
X_T2 = np.transpose(X)
print("transpose函数转置:\n", X_T2.shape)

T属性转置:
 (2, 47)
transpose函数转置:
 (2, 47)


##### 2.2 数组拼接：numpy.vstack()和numpy.hstack()
为X数据添加X0=1的全一列

In [10]:
# 为X数据增加X0=1的全一列
X_all = np.hstack((np.ones((47, 1)), X))
X_all

array([[1.000e+00, 2.104e+03, 3.000e+00],
       [1.000e+00, 1.600e+03, 3.000e+00],
       [1.000e+00, 2.400e+03, 3.000e+00],
       [1.000e+00, 1.416e+03, 2.000e+00],
       [1.000e+00, 3.000e+03, 4.000e+00],
       [1.000e+00, 1.985e+03, 4.000e+00],
       [1.000e+00, 1.534e+03, 3.000e+00],
       [1.000e+00, 1.427e+03, 3.000e+00],
       [1.000e+00, 1.380e+03, 3.000e+00],
       [1.000e+00, 1.494e+03, 3.000e+00],
       [1.000e+00, 1.940e+03, 4.000e+00],
       [1.000e+00, 2.000e+03, 3.000e+00],
       [1.000e+00, 1.890e+03, 3.000e+00],
       [1.000e+00, 4.478e+03, 5.000e+00],
       [1.000e+00, 1.268e+03, 3.000e+00],
       [1.000e+00, 2.300e+03, 4.000e+00],
       [1.000e+00, 1.320e+03, 2.000e+00],
       [1.000e+00, 1.236e+03, 3.000e+00],
       [1.000e+00, 2.609e+03, 4.000e+00],
       [1.000e+00, 3.031e+03, 4.000e+00],
       [1.000e+00, 1.767e+03, 3.000e+00],
       [1.000e+00, 1.888e+03, 2.000e+00],
       [1.000e+00, 1.604e+03, 3.000e+00],
       [1.000e+00, 1.962e+03, 4.00

##### 2.3 reshape 不改变数据的情况下改变数组的形状
使用numpy.arange(9)reshape成(3*3)的数组

In [11]:
x23 = np.arange(9)
x23.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 2.4 flatten 返回一个数据展开后的拷贝，但不改变原本数组
ndarray.flatten(order='C')
将房价数据的标注y变成m*1的二维数组，然后再将二维数组使用flatten()函数展成一个一维数组。

In [12]:
x24 = x23.flatten()
x24

# 将房价数据的标注y变成m*1的二维数组
y = data[:, [2]]
print(y.shape)
# 将m*1的二维数组y使用flatten()函数展成一个一维数组
print(y.flatten().shape)

(47, 1)
(47,)


# 3. 向量/矩阵运算
##### 3.1 向量点积和矩阵乘 numpy.dot()和@运算符
numpy.dot(a, b) 两个数组的点积，也可用于矩阵相乘。还可以用运算符@

In [13]:
n = data.shape[1] - 1
print(n)
w = np.ones((n + 1, 1))
X = X_all.T  #将每个样本以列向量的形式表示,X_all带全1列作为x0
# 计算w^T * X

w.T @ X # 1 * 47

np.dot(w.T, X)

y = data[:, [2]].T

np.power((w.T @ X - y), 2)

2


array([[1.58238475e+11, 1.07778264e+11, 1.34392627e+11, 5.31675976e+10,
        2.88256241e+11, 8.87503681e+10, 9.81957430e+10, 3.90331146e+10,
        4.43590995e+10, 5.80819640e+10, 5.66697069e+10, 1.19022240e+11,
        1.07652891e+11, 4.83603413e+11, 6.68884424e+10, 2.00341284e+11,
        8.91482249e+10, 3.94657956e+10, 2.47390843e+11, 3.55173089e+11,
        6.30657746e+10, 6.40641659e+10, 5.82218293e+10, 6.65294325e+10,
        3.24906840e+11, 6.18994496e+10, 2.14404189e+11, 2.17594261e+11,
        2.23536058e+11, 8.83629131e+10, 1.21144371e+11, 2.85265344e+10,
        9.78782510e+10, 3.32650944e+11, 8.07037191e+10, 6.17318747e+10,
        5.22840236e+10, 1.17555037e+11, 2.96785248e+11, 8.11298379e+10,
        1.34566450e+11, 1.07359765e+11, 9.69873992e+10, 8.86824576e+10,
        3.20571120e+10, 8.88296298e+10, 5.67835538e+10]])

##### 3.2 矩阵求逆 numpy.linalg.inv()
提供了线性代数(linear algebra)函数库 linalg，该库包含了线性代数所需的所有功能

In [14]:
x32 = np.array([[1,2],[3,4]])
print("逆矩阵:\n", np.linalg.inv(x32))

逆矩阵:
 [[-2.   1. ]
 [ 1.5 -0.5]]


##### 3.3 计算矩阵的行列式(determinant) numpy.linalg.det() 

In [15]:
x32 = np.array([[1,2],[3,4]])
print("逆矩阵:\n", np.linalg.inv(x32))

逆矩阵:
 [[-2.   1. ]
 [ 1.5 -0.5]]
